### ISSUE TITLE
Excruciating slow on large dataset

### ISSUE THREAD

**Issue by mspclaims** [bvaughn/react-select-fast-filter-options#24]
I tried to use it with list of ~7K records. Please check CodeSandbox:
https://codesandbox.io/s/5kyy8yxlxl - i.e. try 'back in pain'

Goal is to search by any substring. 

Similar dataset works much faster using plain JQuery / Bootstrap Typeahead (https://github.com/bassjobsen/Bootstrap-3-Typeahead)
Can you please advise if there is some config settings or special technique to make it work fast?

Regards,
VB

**Comment by bvaughn** [comment]
That's because your example is rendering all 7,000+ options each time a character is typed.

I would suggest using the windowed configuration [shown in the docs](https://github.com/bvaughn/react-select-fast-filter-options#react-virtualized-select-example).

Here you go:
https://codesandbox.io/s/y2wq98olx9

**Comment by mspclaims** [comment]
Thanks!! I knew I was missing something obvious :+1:
