### ISSUE TITLE
Calling createFilterOptions function freezes the UI for 8 seconds.

### ISSUE THREAD

**Issue by jobliz** [bvaughn/react-select-fast-filter-options#25]
I've been using react-select-fast-filter-options with 30000+ options. Filtering works snappily and without any problems at all, but calling the createFilterOptions function freezes the UI for approximately 8 seconds. I am using the default configuration without indexing customizations:

```
const filter_options = createFilterOptions({
  labelKey: 'label',
  options: this.state.tags
});
```

[This is the line itself in the code as it is currently running](https://github.com/jobliz/goodbooks10k-dataset-explorer/blob/master/src/views/TagSearch/TagSearch.jsx#L64)

`this.state.tags` is an array taken from the [goodbooks10k dataset](https://github.com/zygmuntz/goodbooks-10k), more specifically, the `tag_name` column of the `tags.csv` file. After reading #18 I had a closer view on the tags and found that some of them have characters in russian, japanese, persian and others; so I tried filtering out the tags which didn't match the `/^([A-Za-z0-9_-]+)$/` regex pattern to keep only those with latin characters, numbers, dashes and underscores. Some thousand tags were excluded and the number still stood over 30000, but the freezing for 8 seconds still happens.

I'm not sure if I'm doing something evident in a very wrong manner or if this kind of delay is to be expected and managed somehow.

**Comment by bvaughn** [comment]
Hi @jobliz 👋

Unfortunately this behavior is expected, depending on how much text is in your data set.

The reason for this is that [`react-select` requires the `filterOptions` function to be synchronous](https://github.com/JedWatson/react-select/blob/e19bce383a8fd1694278de47b6d00a608ea99f2d/src/Select.js#L830). Because of this, this library is built on top of [js-search](https://github.com/bvaughn/js-search) which runs on the UI thread (rather than something like [js-worker-search](https://github.com/bvaughn/js-worker-search) which runs in a web worker). This means that the initial processing of records is blocking and, for large data sets, may cause noticeable jank.

It's still an improvement over the built-in search functionality, since `react-select-fast-filter-options` only pays this cost once rather than [every time the search criteria changes](https://github.com/JedWatson/react-select/blob/e19bce383a8fd1694278de47b6d00a608ea99f2d/src/Select.js#L839, but...it's not ideal.

I'm going to close this issue as "won't fix" because I can't do much about it without changing `react-select`. If you have any ideas though and want to create a PR, I'd be happy to look!
